### ISSUE TITLE
Add endpoints to API files 

### ISSUE THREAD

**Issue by yarelismartin** [nss-evening-cohort-26/pos-terminal-the-algorithm-avengers#30]
User Story
Has all API calls for orders, items and merged data calls 

Acceptance Criteria
Need to create an order.js, 

- [x] -GET ORDER 
- [x] -GET SINGLE ORDER 
- [x] -POST CREATE ORDER
- [x] -PATCH UPDATE ORDER
- [x] -DELETE ORDER

- [x] -GET ITEM
- [x] -POST CREATE ITEM
- [x] -DELETE ITEM

- [x] -GET ORDER ITEMS 
- [x] -DELETE ORDER ITEMS

Dependencies

**Comment by britnay268** [comment]
GET ORDER

- ${endpoint}/orders.json?orderBy="uid"&equalTo="${uid}”

GET SINGLE ORDER 

- ${endpoint}/orders/${firebaseKey}.json

POST CREATE ORDER

- ${endpoint}/orders.json

PATCH UPDATE ORDER

- ${endpoint}/orders/${*payload*.firebaseKey}.json

DELETE ORDER

- ${endpoint}/orders/${*firebaseKey*}.json

**Comment by britnay268** [comment]
GET ITEM

- ${endpoint}/items.json?orderBy="uid"&equalTo="${uid}”

POST CREATE ITEM

- ${endpoint}/items.json

UPDATE ITEMS

- ${endpoint}/items/${*payload*.firebaseKey}.json

DELETE ITEM

- ${endpoint}/items/${*firebaseKey*}.json

GET ORDER ITEMS

- ${endpoint}/orderItems.json?orderBy="uid"&equalTo="${orderFirebaseKey}”

DELETE ORDER ITEMS

- ${endpoint}/orderItems/${*firebaseKey*}.json
