### ISSUE TITLE
Delete Item from Order

### ISSUE THREAD

**Issue by britnay268** [nss-evening-cohort-26/pos-terminal-the-algorithm-avengers#36]
User Story:
As an authenticated user, I should be able to delete an order item from an order.

Acceptance Criteria:
(Really we are deleting an item from an order and placing it back into the items that are not in the order)
- [x] -Create the promise for an item to be deleted.
![311911976-d546cc81-ed47-4ceb-b250-954325b1b553](https://github.com/nss-evening-cohort-26/pos-terminal-the-algorithm-avengers/assets/153968439/67c72d25-c053-4674-9bb0-d620744d7bd3)
- [ ] -Add eventListener in domEvents.js
- [x] -Need to create a promise to DELETE orderItem
![image](https://github.com/nss-evening-cohort-26/pos-terminal-the-algorithm-avengers/assets/153968439/2b7a92b9-6948-4d46-a48a-99fb0998f219)

![image](https://github.com/nss-evening-cohort-26/pos-terminal-the-algorithm-avengers/assets/153968439/12b885bd-c76f-4378-82a3-bf452bdcb1ec)

![image](https://github.com/nss-evening-cohort-26/pos-terminal-the-algorithm-avengers/assets/153968439/924029ee-bdeb-4dd5-8204-93f19c7684d7)

Dependencies:
OrderDetails.js need to exist to delete the item from the order.

**Comment by ajawashington** [comment]
@britnay268 Something to note, this will require a merged data call. You will be removing a OrderItem, your many to many node. Not removing an item from the database since you are reusing those.
