### ISSUE TITLE
Close Order 

### ISSUE THREAD

**Issue by britnay268** [nss-evening-cohort-26/pos-terminal-the-algorithm-avengers#37]
User Story:
As an authenticated user, when I'm looking at an order, I should be able to click a button that will take me to a Close Order Form. I should be able to input the following information:
Payment Type (cash, check, debit, credit, or mobile-payment)
Tip Amount
As an authenticated user, when I submit the Close Order form, the order's status should change from "Open" to "Closed".

Acceptance Criteria:
- [x] -Event listener in the domEvents to render payment form
- [x] -Create form for "Go To Payment" button (paymentForm.js)
- [x] -Event listener in form events to close the order when the "Close Order" button is clicked.
![image](https://github.com/nss-evening-cohort-26/pos-terminal-the-algorithm-avengers/assets/153968439/d8fb5bd9-2c1c-433c-855f-04c276f1d8f7)

Thoughts on how to do this: Pulling from the order detail total in order to then add that amount with our tips from the close order form which will then be going into our payload that is posting this new data into our dataset.

Dependencies:
orderDetails.js need to be created to get to get to the payment Form
Need create a Revenue entry promise to get revenue data
Need the showRevenue.js file to show the revenue data on the page.

**Comment by yarelismartin** [comment]
We would need a POST to create revenue that is triggered from the 'close order' btn so that when the revenue page is loaded it will have this new data in the revenue data set.  Maybe need to use a async and await so we wait  for the post before rendering the revenue page???

**Comment by britnay268** [comment]
In the user story, it does not get to that point of showing the revenue page yet. I think that should be a separate ticket as there is a lot already going on there
