### ISSUE TITLE
Read Revenue

### ISSUE THREAD

**Issue by britnay268** [nss-evening-cohort-26/pos-terminal-the-algorithm-avengers#38]
User Story:
As an authenticated user, when I submit the Close Order form, a new revenue node is created with the following information:
Total Order Amount (including tip)
Date
Payment Type
Tip Amount
Order Type
As an authenticated user, I should NOT be able to close an order that has already been closed.
As an authenticated user, I should be able to see the sum of all of the Revenue made to date.

Acceptance Criteria:
- [ ] -Need to create a promise to get (READ) revenue
- [ ] -Need to create showRevenue.js file to show the revenue with relevant data
- [ ] -Need to edit form events so when "Close Order" button is pressed, it shows the Revenue page.
- [ ]  -When Close Order is clicked, it should POST a new revenue node into revenue dataset

![image](https://github.com/nss-evening-cohort-26/pos-terminal-the-algorithm-avengers/assets/153968439/acad2807-be28-40aa-a19d-f38acb8ee8ec)

Dependencies:
The Order details page must be fully functional meaning when "Go To Payment" button is pressed, it shows the payment form to press the "Close Order" button to generate the Revenue page.

**Comment by yarelismartin** [comment]
Thoughts on how to do this: Pulling from the order detail total in order to then add that amount with our tips from the close order form which will then be going into our payload that is posting this new data into our dataset.
